-- ================================================================
-- SEED 02: PERMISSIONS + ROLE–PERMISSION MAPPING (wildcard)
-- ================================================================

-- ----------------------------------------------------------------
-- PHẦN 1: DANH MỤC PERMISSION
-- ----------------------------------------------------------------
INSERT INTO permissions (code, description, is_active) VALUES
  ('hrm.profile.read',              'Xem hồ sơ cán bộ',                        TRUE),
  ('hrm.profile.write',             'Tạo / cập nhật hồ sơ',                    TRUE),
  ('hrm.profile.approve',           'Duyệt hồ sơ',                             TRUE),
  ('hrm.profile.reject',            'Trả hồ sơ về draft',                      TRUE),
  ('hrm.profile.export',            'Xuất danh sách cán bộ',                   TRUE),
  ('hrm.profile.delete',            'Xóa mềm hồ sơ',                           TRUE),
  ('hrm.profile.status',            'Thay đổi trạng thái công tác',            TRUE),
  ('hrm.recruitment.read',          'Xem đề xuất tuyển dụng',                  TRUE),
  ('hrm.recruitment.write',         'Tạo / sửa đề xuất tuyển dụng',            TRUE),
  ('hrm.recruitment.approve',       'Phê duyệt tuyển dụng',                    TRUE),
  ('hrm.recruitment.export',        'Xuất danh sách ứng viên',                 TRUE),
  ('hrm.contract.read',             'Xem hợp đồng',                            TRUE),
  ('hrm.contract.write',            'Tạo / sửa hợp đồng',                      TRUE),
  ('hrm.contract.approve',          'Ký duyệt hợp đồng',                       TRUE),
  ('hrm.contract.terminate',        'Chấm dứt hợp đồng',                       TRUE),
  ('hrm.contract.extend',           'Gia hạn hợp đồng',                        TRUE),
  ('hrm.contract.export',           'Xuất danh sách HĐ sắp hết hạn',           TRUE),
  ('hrm.salary.read',               'Xem thông tin lương',                     TRUE),
  ('hrm.salary.self_read',          'Tự xem lương bản thân',                   TRUE),
  ('hrm.salary.write',              'Cập nhật lương',                          TRUE),
  ('hrm.salary.approve',            'Phê duyệt nâng bậc lương',                TRUE),
  ('hrm.salary.propose',            'Lập đề xuất nâng bậc',                    TRUE),
  ('hrm.salary.export',             'Xuất báo cáo lương',                      TRUE),
  ('hrm.appointment.read',          'Xem quyết định bổ nhiệm',                 TRUE),
  ('hrm.appointment.write',         'Tạo / sửa hồ sơ bổ nhiệm',               TRUE),
  ('hrm.appointment.approve',       'Phê duyệt bổ nhiệm',                      TRUE),
  ('hrm.appointment.ballot',        'Bỏ phiếu tín nhiệm',                      TRUE),
  ('hrm.appointment.dismiss',       'Ra quyết định miễn nhiệm',                TRUE),
  ('hrm.appointment.extend',        'Kéo dài thời gian chức vụ',               TRUE),
  ('hrm.appointment.export',        'Xuất danh sách bổ nhiệm',                 TRUE),
  ('hrm.appointment.alert_read',    'Cảnh báo bổ nhiệm sắp hết hạn',           TRUE),
  ('hrm.workload.read',             'Xem định mức KLGD đơn vị',                TRUE),
  ('hrm.workload.self_read',        'Tự xem định mức KLGD cá nhân',            TRUE),
  ('hrm.workload.write',            'Khai báo minh chứng KLGD',                TRUE),
  ('hrm.workload.approve',          'Xét duyệt minh chứng KLGD',               TRUE),
  ('hrm.workload.admin',            'Cài đặt tham số định mức',                TRUE),
  ('hrm.workload.finalize',         'Chốt tổng hợp KLGD',                      TRUE),
  ('hrm.workload.export',           'Xuất báo cáo KLGD',                       TRUE),
  ('hrm.reward.read',               'Xem hồ sơ thi đua',                       TRUE),
  ('hrm.reward.self_read',          'Tự xem khen thưởng bản thân',             TRUE),
  ('hrm.reward.write',              'Tạo / sửa hồ sơ thi đua',                TRUE),
  ('hrm.reward.approve',            'Phê duyệt hồ sơ thi đua',                TRUE),
  ('hrm.reward.ballot',             'Bỏ phiếu bình xét thi đua',               TRUE),
  ('hrm.reward.finalize',           'Chốt kết quả bình xét',                   TRUE),
  ('hrm.reward.export',             'Xuất báo cáo thi đua',                    TRUE),
  ('hrm.reward.discipline',         'Ghi nhận / duyệt kỷ luật',                TRUE),
  ('hrm.stats.unit.read',           'Thống kê nhân sự cấp đơn vị',             TRUE),
  ('hrm.stats.school.read',         'Thống kê nhân sự toàn trường',            TRUE),
  ('hrm.stats.salary.read',         'Báo cáo lương',                           TRUE),
  ('hrm.stats.workload.read',       'Báo cáo KLGD tổng hợp',                   TRUE),
  ('hrm.stats.reward.read',         'Báo cáo thi đua khen thưởng',             TRUE),
  ('hrm.notification.read',         'Đọc thông báo',                           TRUE),
  ('hrm.notification.send',         'Gửi thông báo thủ công',                  TRUE),
  ('hrm.notification.manage',       'Quản lý template thông báo',              TRUE),
  ('hrm.attachment.upload',         'Upload file đính kèm',                    TRUE),
  ('hrm.attachment.download',       'Tải file đính kèm',                       TRUE),
  ('hrm.attachment.delete',         'Xóa file đính kèm',                       TRUE),
  ('hrm.attachment.verify',         'Xác minh văn bản đính kèm',               TRUE),
  ('hrm.workflow.read',             'Xem trạng thái quy trình',                TRUE),
  ('hrm.workflow.advance',          'Chuyển bước tiếp theo',                   TRUE),
  ('hrm.workflow.cancel',           'Hủy quy trình',                           TRUE),
  ('hrm.org.read',                  'Xem cơ cấu tổ chức',                      TRUE),
  ('hrm.org.write',                 'Tạo / sửa đơn vị tổ chức',               TRUE),
  ('system.auth.role.grant',        'Gán / thu hồi vai trò',                   TRUE),
  ('system.auth.user.manage',       'Tạo / sửa / vô hiệu hóa tài khoản',      TRUE),
  ('system.auth.password.reset',    'Đặt lại mật khẩu',                        TRUE),
  ('system.auth.permission.manage', 'Quản lý danh mục permission',             TRUE),
  ('system.auth.role.manage',       'Tạo / sửa / xóa vai trò',                TRUE),
  ('system.audit.read',             'Xem nhật ký hệ thống',                    TRUE),
  ('system.audit.export',           'Xuất nhật ký audit',                      TRUE),
  ('system.config.read',            'Xem cấu hình hệ thống',                   TRUE),
  ('system.config.write',           'Sửa cấu hình hệ thống',                   TRUE),
  ('system.scheduler.manage',       'Quản lý cron jobs',                        TRUE)
ON CONFLICT (code) DO UPDATE SET
  description = EXCLUDED.description,
  is_active   = EXCLUDED.is_active;
